name: hybridmodels
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  # Core scientific python
  - numpy=1.21              # compatibility with numba and pysal
  - pyqt
  - tqdm                    # progress bars
  # Plotting
  - matplotlib              # plotting
  # Spatial packages
  - pysal                   # for spatial data analytics [problematic]
  - pyshp                   # reading ESRI shapefiles
  - pyproj>=3.0             # reprojecting pyshp objects
  - rasterio                # manipulating rasters
  - rasterstats             # summarise raster datasets
  - geopy                   # get geocodes for locations
  - cartopy                 # plotting maps
  - folium                  # plot interactive map
  - descartes               # shapely / GeoJSON to matplotlib patches
  - folium                  # for interactive maps
  - geojson                 # manipulate geoJSONs
  - xarray                  # use with sentnelhub
  - rioxarray>=0.3.0        # extends xarray with rasterio backend
  - scipy                   # scientific computing
  - geopandas
  - dask-geopandas
  - richdem
  - pyogrio                 # required for dask_geopandas.read_file()
  # APIs
  - earthengine-api         # access Google Earth Engine
  - sentinelhub             # access SentinelHub
  # Jupyter Environment
  - ipykernel               # attach environment to Jupyter notebook functionality
  - notebook                # Jupyter notebook
  # Machine learning
  # - tensorflow

# conda env create -f environment.yml
# python -m ipykernel install --user --n hybridmodels

# conda env remove -n hybridmodels
# conda info --envs
