name: hybridmodels-modelbuild
# If issues with pyg use wheels installation described in pyg docs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  # Core scientific python
  - numpy                   # compatibility with numba and pysal
  - tqdm                    # progress bars
  - networkx
  # Plotting
  - matplotlib              # plotting
  # Spatial packages
  - scipy                   # scientific computing
  - pysal                   # for spatial data analytics [problematic]
  - geopandas
# Jupyter Environment
  - ipykernel               # attach environment to Jupyter notebook functionality
  - notebook                # Jupyter notebook
  # Machine learning
  - scikit-learn
  - tensorflow              # keras submodule
  - pytorch                 # neural networks

# conda env create -f environment2.yml --experimental-solver=libmamba
# conda activate hybridmodels-modelbuild
# python -m ipykernel install --user --name hybridmodels-modelbuild

# conda env remove -n hybridmodels
# conda info --envs
